"""Generate Phase 3 COSMOS paper-convergence Bayesian-method figures."""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path

import pandas as pd

from paper_bayesian_method import (
    compute_combined_scores_by_bin,
    merge_ps_scores,
    plot_fig2_1_prior,
    plot_fig2_2_slice_fits,
    plot_fig2_3_residuals,
    plot_fig2_4_ps_map,
    plot_fig2_5_ps_vs_extendedness,
    plot_fig2_6_multiband,
    plot_fig2_7_method_color_color,
)
from paper_sample_selection import PaperPaths, load_cosmos_dp2, prepare_phase1_samples


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _append_manifest(repo_root: Path, generated: list[dict]) -> None:
    manifest = repo_root / "paper_convergence/docs/figure_manifest.md"
    existing = manifest.read_text(encoding="utf-8") if manifest.exists() else "# Figure Manifest\n"
    marker = "\n## Phase 3: Bayesian Method Figures\n"
    content = existing.split(marker)[0].rstrip() + marker
    for row in generated:
        content += (
            f"\n### {row['figure_id']}\n"
            f"- Filename: `{row['filename']}`\n"
            f"- Generated by: `paper_convergence/code/run_paper_phase3_cosmos.py`\n"
            f"- Caption draft: {row['caption']}\n"
            f"- Sample definition: {row['sample']}\n"
            f"- Caveats: {row['caveats']}\n"
            f"- Status: {row['status']}\n"
        )
    _write_text(manifest, content + "\n")


def _load_ps_with_dp2(repo_root: Path) -> pd.DataFrame:
    paths = PaperPaths.from_repo_root(repo_root)
    dp2 = load_cosmos_dp2(paths)
    ps = pd.read_parquet(paths.repo_root / "outputs/dp2_cosmos_ps_v8.parquet")
    return dp2.merge(ps.drop_duplicates("object_id"), on="object_id", how="left")


def _write_prior_notes(repo_root: Path, has_logl: bool) -> Path:
    path = repo_root / "paper_convergence/results/section2_bayesian_method/pS_prior_update_notes.md"
    text = f"""# pS Prior Update Notes

Generated: {datetime.now().isoformat(timespec='seconds')}

The available v8 pS file was checked for log-likelihood components.

- `logL_star/logL_galaxy` available: {has_logl}
- Existing columns used for this phase: `pS_u`, `pS_g`, `pS_r`, `pS_i`, `pS_z`, `pS_y`

Because the required likelihood components are not available, this phase does not apply Eq. 54 prior calibration. Figures that use pS or empirical likelihood scores are labeled as `no Eq. 54 prior calibration yet`.

Needed for proper prior calibration:

1. per-object `logL_star` and `logL_galaxy`, or equivalent recoverable likelihood ratio components;
2. magnitude-dependent prior from Fig 2.1;
3. posterior update via `posterior_log_odds_star = logL_star - logL_galaxy + log[p_star_prior(m) / p_gal_prior(m)]`.
"""
    _write_text(path, text)
    return path


def run_phase3(repo_root: Path) -> dict[str, list[Path]]:
    samples = prepare_phase1_samples(repo_root)
    matched = samples["matched_paper"]
    dp2 = samples["dp2_paper"]
    dp2_ps = _load_ps_with_dp2(repo_root)
    ps_cols = set(pd.read_parquet(repo_root / "outputs/dp2_cosmos_ps_v8.parquet").columns)
    has_logl = bool({"logL_star", "logL_galaxy"}.issubset(ps_cols))
    matched_ps = merge_ps_scores(matched, pd.read_parquet(repo_root / "outputs/dp2_cosmos_ps_v8.parquet"))

    out_fig = repo_root / "paper_convergence/figures/section2_bayesian_method"
    out_res = repo_root / "paper_convergence/results/section2_bayesian_method"
    out_log = repo_root / "paper_convergence/logs"
    out_fig.mkdir(parents=True, exist_ok=True)
    out_res.mkdir(parents=True, exist_ok=True)
    out_log.mkdir(parents=True, exist_ok=True)

    outputs: dict[str, list[Path]] = {}

    fig, table = plot_fig2_1_prior(matched, out_fig / "fig2_1_cosmos_star_galaxy_prior_vs_rmag.png")
    path = out_res / "fig2_1_cosmos_star_galaxy_prior_vs_rmag_table.csv"
    table.to_csv(path, index=False)
    notes = out_res / "fig2_1_cosmos_star_galaxy_prior_notes.md"
    _write_text(notes, "Prior table is based on matched COSMOS2020 star/galaxy counts in 0.5 mag bins using uncorrected r CModel magnitude.\n")
    outputs["fig2_1"] = fig + [path, notes]

    fig, summary = plot_fig2_2_slice_fits(dp2, out_fig / "fig2_2_cosmos_r_delta_slice_fits_2x4.png")
    path = out_res / "fig2_2_cosmos_r_delta_slice_fits_2x4_summary.csv"
    summary.to_csv(path, index=False)
    outputs["fig2_2"] = fig + [path]

    fig, summary = plot_fig2_3_residuals(dp2, out_fig / "fig2_3_cosmos_ury_data_model_residuals_3x3.png")
    path = out_res / "fig2_3_cosmos_ury_data_model_residuals_3x3_summary.csv"
    summary.to_csv(path, index=False)
    outputs["fig2_3"] = fig + [path]

    fig, summary = plot_fig2_4_ps_map(dp2_ps, out_fig / "fig2_4_cosmos_r_pS_map_16_26.png")
    path = out_res / "fig2_4_cosmos_r_pS_map_16_26_summary.csv"
    summary.to_csv(path, index=False)
    prior_notes = _write_prior_notes(repo_root, has_logl)
    outputs["fig2_4"] = fig + [path, prior_notes]

    fig, summary = plot_fig2_5_ps_vs_extendedness(
        matched_ps,
        out_fig / "fig2_5_cosmos_single_band_pS_vs_r_extendedness_performance.png",
    )
    path = out_res / "fig2_5_cosmos_single_band_pS_vs_r_extendedness_performance_summary.csv"
    summary.to_csv(path, index=False)
    outputs["fig2_5"] = fig + [path]

    fig, summary, density = plot_fig2_6_multiband(
        matched_ps,
        out_fig / "fig2_6_cosmos_multiband_r_gri_ugrizy_performance.png",
    )
    path = out_res / "fig2_6_cosmos_multiband_r_gri_ugrizy_performance_summary.csv"
    summary.to_csv(path, index=False)
    density_path = out_res / "combined_band_likelihood_summary.csv"
    summary.to_csv(density_path, index=False)
    density_diag_path = out_res / "combined_band_likelihood_density_diagnostics.csv"
    density.to_csv(density_diag_path, index=False)
    outputs["fig2_6"] = fig + [path, density_path, density_diag_path]

    scored, density_for_labels = compute_combined_scores_by_bin(matched_ps)
    fig, summary = plot_fig2_7_method_color_color(
        scored,
        out_fig / "fig2_7_cosmos_ugrizy_method_color_color_2x4.png",
    )
    path = out_res / "fig2_7_cosmos_ugrizy_method_color_color_2x4_summary.csv"
    summary.to_csv(path, index=False)
    label_density_path = out_res / "fig2_7_cosmos_ugrizy_method_density_diagnostics.csv"
    density_for_labels.to_csv(label_density_path, index=False)
    outputs["fig2_7"] = fig + [path, label_density_path]

    manifest_rows = [
        {
            "figure_id": "Fig 2.1",
            "filename": "paper_convergence/figures/section2_bayesian_method/fig2_1_cosmos_star_galaxy_prior_vs_rmag.png",
            "caption": "COSMOS matched star/galaxy count-ratio prior as a function of uncorrected r CModel magnitude.",
            "sample": "COSMOS2020-matched paper sample.",
            "caveats": "Prior is empirical from matched labels only.",
            "status": "main paper candidate",
        },
        {
            "figure_id": "Fig 2.2",
            "filename": "paper_convergence/figures/section2_bayesian_method/fig2_2_cosmos_r_delta_slice_fits_2x4.png",
            "caption": "COSMOS r-band psfMag-CModelMag slice distributions in display magnitude bins.",
            "sample": "COSMOS DP2 paper sample.",
            "caveats": "First-pass display guide uses robust Gaussian overlays, not Eq.54 prior calibration.",
            "status": "main paper candidate",
        },
        {
            "figure_id": "Fig 2.3",
            "filename": "paper_convergence/figures/section2_bayesian_method/fig2_3_cosmos_ury_data_model_residuals_3x3.png",
            "caption": "COSMOS u/r/y data, smoothed row model, and residuals in psfMag-CModelMag versus CModel magnitude.",
            "sample": "COSMOS DP2 paper sample.",
            "caveats": "First-pass residual display; full model2D fitting can replace the smoothed row model later.",
            "status": "diagnostic only",
        },
        {
            "figure_id": "Fig 2.4",
            "filename": "paper_convergence/figures/section2_bayesian_method/fig2_4_cosmos_r_pS_map_16_26.png",
            "caption": "COSMOS r-band v8 pS map in morphology-magnitude space.",
            "sample": "COSMOS DP2 paper sample.",
            "caveats": "No Eq.54 prior calibration yet because log-likelihood components are unavailable.",
            "status": "main paper candidate",
        },
        {
            "figure_id": "Fig 2.5",
            "filename": "paper_convergence/figures/section2_bayesian_method/fig2_5_cosmos_single_band_pS_vs_r_extendedness_performance.png",
            "caption": "COSMOS r-band pS ROC compared with r-band extendedness operating point.",
            "sample": "COSMOS2020-matched paper sample.",
            "caveats": "Draft/no Eq.54 prior calibration yet.",
            "status": "main paper candidate",
        },
        {
            "figure_id": "Fig 2.6",
            "filename": "paper_convergence/figures/section2_bayesian_method/fig2_6_cosmos_multiband_r_gri_ugrizy_performance.png",
            "caption": "COSMOS empirical likelihood performance for r, gri, and ugrizy band combinations.",
            "sample": "COSMOS2020-matched paper sample.",
            "caveats": "Same-bin empirical likelihood draft/no Eq.54 prior calibration yet.",
            "status": "main paper candidate",
        },
        {
            "figure_id": "Fig 2.7",
            "filename": "paper_convergence/figures/section2_bayesian_method/fig2_7_cosmos_ugrizy_method_color_color_2x4.png",
            "caption": "COSMOS color-color diagrams classified by ugrizy empirical likelihood method labels.",
            "sample": "COSMOS2020-matched paper sample.",
            "caveats": "Method labels use logL_star-logL_galaxy >= 0; no Eq.54 prior calibration yet.",
            "status": "appendix candidate",
        },
    ]
    _append_manifest(repo_root, manifest_rows)

    lines = [
        "# Phase 3 Generation Summary",
        "",
        f"Generated: {datetime.now().isoformat(timespec='seconds')}",
        "",
        "## Completed",
    ]
    for key, paths in outputs.items():
        lines.append(f"- {key}:")
        for p in paths:
            lines.append(f"  - `{p.relative_to(repo_root)}`")
    lines += [
        "",
        "## Missing Or Deferred",
        "- Eq.54 prior-calibrated pS was not implemented because `outputs/dp2_cosmos_ps_v8.parquet` does not contain `logL_star`/`logL_galaxy` components.",
        "- Fig 2.2 and Fig 2.3 are first-pass display/model diagnostics; full production mixture/model2D fitting can replace these if the final model-fitting products are provided.",
        "",
        "## Assumptions",
        "- Larger pS means more star-like.",
        "- Positive class in performance plots is COSMOS2020 external star.",
        "- Common magnitude reference is uncorrected r-band CModel magnitude.",
    ]
    log_path = out_log / "phase3_generation_summary.md"
    _write_text(log_path, "\n".join(lines) + "\n")
    outputs["logs"] = [log_path]
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    outputs = run_phase3(args.repo_root.resolve())
    print("[PHASE 3 COMPLETE]")
    for key, paths in outputs.items():
        print(f"{key}:")
        for path in paths:
            print(f"  {path}")


if __name__ == "__main__":
    main()

